#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Views\Shared\_Toastr.cshtml"
    using Arezoo.Web.Views.Shared;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\Shared\_Toastr.cshtml"
    using Clinic.FrameWork.Toast;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Toastr.cshtml")]
    public partial class _Views_Shared__Toastr_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Toastr_cshtml()
        {
        }
        public override void Execute()
        {


WriteLiteral("\r\n");




            
            #line 6 "..\..\Views\Shared\_Toastr.cshtml"
 if (TempData.ContainsKey("Toastr"))
{
    Toastr toastr = TempData["Toastr"] as Toastr;
    
            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Shared\_Toastr.cshtml"
Write(ToastrBuilder.ShowToastMessages(toastr));

            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Shared\_Toastr.cshtml"
                                            ;
}

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
