using Clinic.FrameWork.Toast;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arezoo.Web.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 5 "..\..\Views\Shared\ToastrBuilder.cshtml"
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public static class ToastrBuilder
    {

public static System.Web.WebPages.HelperResult ShowToastMessages(Toastr toastr)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 7 "..\..\Views\Shared\ToastrBuilder.cshtml"
 
    if (toastr != null)
    {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <script>\r\n            $(document).ready(function () {\r\n                to" +
"astr.options.closeButton = \'");



#line 12 "..\..\Views\Shared\ToastrBuilder.cshtml"
   WebViewPage.WriteTo(@__razor_helper_writer, toastr.ShowCloseButton);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\';\r\n                toastr.options.newestOnTop = \'");



#line 13 "..\..\Views\Shared\ToastrBuilder.cshtml"
   WebViewPage.WriteTo(@__razor_helper_writer, toastr.ShowNewestOnTop);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\';\r\n\r\n");



#line 15 "..\..\Views\Shared\ToastrBuilder.cshtml"
                 foreach (ToastMessage message in toastr.ToastMessages)
                {
                    string toastTypeValue = message.ToastType.ToString("F").ToLower();

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                    ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " var optionsOverride = { /* Add message specific options here */ \"positionClass\":" +
" \"toast-top-center\", \"closeButton\": false, \"progressBar\": true };\r\n");



#line 19 "..\..\Views\Shared\ToastrBuilder.cshtml"
                    if (message.IsSticky)
                    {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                        ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "optionsOverride.timeOut = 5000; \r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                        ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "optionsOverride.extendedTimeout = 1000;\r\n");



#line 23 "..\..\Views\Shared\ToastrBuilder.cshtml"
                    }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                    ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "toastr[\'");



#line 24 "..\..\Views\Shared\ToastrBuilder.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, toastTypeValue);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\'](\'");



#line 24 "..\..\Views\Shared\ToastrBuilder.cshtml"
      WebViewPage.WriteTo(@__razor_helper_writer, message.Message);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\', \'");



#line 24 "..\..\Views\Shared\ToastrBuilder.cshtml"
                          WebViewPage.WriteTo(@__razor_helper_writer, message.Title);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\', optionsOverride);\r\n");



#line 25 "..\..\Views\Shared\ToastrBuilder.cshtml"
                }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            });\r\n        </script>\r\n");



#line 28 "..\..\Views\Shared\ToastrBuilder.cshtml"
    }

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
