// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC
{
    public class SharedController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _Toastr = "_Toastr";
                public readonly string CheckBoxListBuilder = "CheckBoxListBuilder";
                public readonly string DatePickerInitial = "DatePickerInitial";
                public readonly string ToastrBuilder = "ToastrBuilder";
            }
            public readonly string _Toastr = "~/Views/Shared/_Toastr.cshtml";
            public readonly string CheckBoxListBuilder = "~/Views/Shared/CheckBoxListBuilder.cshtml";
            public readonly string DatePickerInitial = "~/Views/Shared/DatePickerInitial.cshtml";
            public readonly string ToastrBuilder = "~/Views/Shared/ToastrBuilder.cshtml";
            static readonly _DisplayTemplatesClass s_DisplayTemplates = new _DisplayTemplatesClass();
            public _DisplayTemplatesClass DisplayTemplates { get { return s_DisplayTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _DisplayTemplatesClass
            {
                public readonly string CanonicalHelperModel = "CanonicalHelperModel";
                public readonly string MenuHelperModel = "MenuHelperModel";
                public readonly string MetaRobotsHelperModel = "MetaRobotsHelperModel";
                public readonly string SiteMapHelperModel = "SiteMapHelperModel";
                public readonly string SiteMapNodeModel = "SiteMapNodeModel";
                public readonly string SiteMapNodeModelList = "SiteMapNodeModelList";
                public readonly string SiteMapPath = "SiteMapPath";
                public readonly string SiteMapPathHelperModel = "SiteMapPathHelperModel";
                public readonly string SiteMapTitleHelperModel = "SiteMapTitleHelperModel";
            }
            static readonly _KendoTemplatesClass s_KendoTemplates = new _KendoTemplatesClass();
            public _KendoTemplatesClass KendoTemplates { get { return s_KendoTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _KendoTemplatesClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string UploadTemplate = "UploadTemplate";
                }
                public readonly string UploadTemplate = "~/Views/Shared/KendoTemplates/UploadTemplate.cshtml";
            }
            static readonly _MasterTemplatesClass s_MasterTemplates = new _MasterTemplatesClass();
            public _MasterTemplatesClass MasterTemplates { get { return s_MasterTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _MasterTemplatesClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string _Layout = "_Layout";
                    public readonly string _MainHeader = "_MainHeader";
                    public readonly string _MainSideBar = "_MainSideBar";
                }
                public readonly string _Layout = "~/Views/Shared/MasterTemplates/_Layout.cshtml";
                public readonly string _MainHeader = "~/Views/Shared/MasterTemplates/_MainHeader.cshtml";
                public readonly string _MainSideBar = "~/Views/Shared/MasterTemplates/_MainSideBar.cshtml";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
