// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static partial class MVC
{
    public static Clinic.Web.Controllers.AccountController Account = new Clinic.Web.Controllers.T4MVC_AccountController();
    public static Clinic.Web.Controllers.ActivityLogController ActivityLog = new Clinic.Web.Controllers.T4MVC_ActivityLogController();
    public static Clinic.Web.Controllers.AddressController Address = new Clinic.Web.Controllers.T4MVC_AddressController();
    public static Clinic.Web.Controllers.AuditLogController AuditLog = new Clinic.Web.Controllers.T4MVC_AuditLogController();
    public static Clinic.Web.Controllers.BaseController Base = new Clinic.Web.Controllers.T4MVC_BaseController();
    public static Clinic.Web.Controllers.DoctorController Doctor = new Clinic.Web.Controllers.T4MVC_DoctorController();
    public static Clinic.Web.Controllers.DocumentController Document = new Clinic.Web.Controllers.T4MVC_DocumentController();
    public static Clinic.Web.Controllers.EmailController Email = new Clinic.Web.Controllers.T4MVC_EmailController();
    public static Clinic.Web.Controllers.ErrorController Error = new Clinic.Web.Controllers.T4MVC_ErrorController();
    public static Clinic.Web.Controllers.ExpertiseController Expertise = new Clinic.Web.Controllers.T4MVC_ExpertiseController();
    public static Clinic.Web.Controllers.FileController File = new Clinic.Web.Controllers.T4MVC_FileController();
    public static Clinic.Web.Controllers.HomeController Home = new Clinic.Web.Controllers.T4MVC_HomeController();
    public static Clinic.Web.Controllers.PatientController Patient = new Clinic.Web.Controllers.T4MVC_PatientController();
    public static Clinic.Web.Controllers.PresenterController Presenter = new Clinic.Web.Controllers.T4MVC_PresenterController();
    public static Clinic.Web.Controllers.ProductBuyController ProductBuy = new Clinic.Web.Controllers.T4MVC_ProductBuyController();
    public static Clinic.Web.Controllers.ProductController Product = new Clinic.Web.Controllers.T4MVC_ProductController();
    public static Clinic.Web.Controllers.ProductSellerController ProductSeller = new Clinic.Web.Controllers.T4MVC_ProductSellerController();
    public static Clinic.Web.Controllers.ReportController Report = new Clinic.Web.Controllers.T4MVC_ReportController();
    public static Clinic.Web.Controllers.RoleController Role = new Clinic.Web.Controllers.T4MVC_RoleController();
    public static Clinic.Web.Controllers.SmsController Sms = new Clinic.Web.Controllers.T4MVC_SmsController();
    public static Clinic.Web.Controllers.StatisticController Statistic = new Clinic.Web.Controllers.T4MVC_StatisticController();
    public static Clinic.Web.Controllers.UserController User = new Clinic.Web.Controllers.T4MVC_UserController();
    public static T4MVC.SharedController Shared = new T4MVC.SharedController();
}

namespace T4MVC
{
}

#pragma warning disable 0436
namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}
#pragma warning restore 0436

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ActionResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_JsonResult : System.Web.Mvc.JsonResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_JsonResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_Clinic_FrameWork_Results_CaptchaImageResult : Clinic.FrameWork.Results.CaptchaImageResult, IT4MVCActionResult
{
    public T4MVC_Clinic_FrameWork_Results_CaptchaImageResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace Links
{
    
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Bundles
    {
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        string path = VirtualPathUtility.ToAbsolute(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;

    // Calling T4Extension.TimestampString through delegate to allow it to be replaced for unit testing and other purposes
    public static Func<string, string> TimestampString = System.Web.Mvc.T4Extensions.TimestampString;

    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}





#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114


